(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
var circular={version:"0.0.2",currentId:1,showWarnings:!1,classes:{}};module.exports=circular,circular.registerClass=function(r,c,e){e||(e={}),e.prototype=c,circular.classes[r]=e},circular.register=function(r){return{type:r,uid:circular.currentId++}},circular.setSafe=function(){return{isCircularSafe:!0}},circular.serialize=function(r){var c={},e=circular._serializeObject(r,c),i={object:e,references:c};return JSON.stringify(i)},circular.parse=function(r,c){var e=JSON.parse(r),i=[];return circular._deserializeObject(e.object,e.references,i,c)},circular._serializeObject=function(r,c){var e=null;if(e=circular.isArray(r)?new Array:{},!r._c&&!circular.isArray(r))throw console.log(r),"ERROR: "+typeof r+" without Circular metadata...";circular.isArray(r)||(c["x"+r._c.uid]=e);for(var i in r){var a=i,t=r[a];if((circular.isArray(r)||!circular._isTransient(r._c.type,a))&&"function"!=typeof t)if("_c"===a)e[a]=t;else if(circular.isArray(t))e[a]=circular._serializeObject(t,c);else if(null==t||"object"!=typeof t)e[a]=t;else{if(!t._c)throw r._c?"ERROR: "+a+" attribute from circular type "+r._c.type+" has no Circular metadata":"ERROR: ["+a+"] attribute from non circular object has no Circular metadata";t._c.isCircularSafe?e[a]=r[a]:(c["x"+t._c.uid]||(c["x"+t._c.uid]=circular._serializeObject(t,c)),e[a]=t._c)}}return e},circular._isTransient=function(r,c){return circular.classes[r]&&circular.classes[r].transients&&circular.classes[r].transients[c]},circular._deserializeObject=function(r,c,e,i){var a=null;circular.isArray(r)?a=[]:r._c&&(circular.classes[r._c.type]&&circular.classes[r._c.type].prototype?a=new circular.classes[r._c.type].prototype:(circular.showWarnings&&console.log("Warning: prototype for "+r._c.type+" was not found, using {}"),a={}),e["x"+r._c.uid]=a,r._c.uid>circular.currentId&&(circular.currentId=r._c.uid));for(var t in r){var u=t,s=r[u];"_c"===u?a[u]=r[u]:circular.isArray(s)?a[u]=circular._deserializeObject(s,c,e,i):s&&"object"==typeof s&&s.type&&s.uid?(e["x"+s.uid]||(circular._deserializeObject(c["x"+s.uid],c,e,i),circular.classes[s.type]&&circular.classes[s.type].reviver&&circular.classes[s.type].reviver(e["x"+s.uid],i)),a[u]=e["x"+s.uid]):a[u]=s}return a},circular.isArray=function(r){return"[object Array]"===Object.prototype.toString.call(r)};


},{}],2:[function(require,module,exports){
function assert(e,r){return e?0:(console.log("Assertion failed: "+r),1)}var circular=require("./circular"),circularTests={runTests:function(){console.log("Running Test 1"),circularTests.test(),console.log("Running Test 2"),circularTests.testReviversAndTransients()},test:function(){var e={_c:{uid:1,type:"Country"},name:"Colombia"},r=[{_c:{uid:2,type:"Person"},name:"Jhon",age:400,country:e},{_c:{uid:3,type:"Person"},name:"Sarah",age:300,country:e}];e.leader=r[0];var n=circular.serialize(r),s=circular.parse(n),t=0;t+=assert(r.length===s.length,"people.length === deserialized.length"),t+=assert(r[0].name===s[0].name,"people[0].name === deserialized[0].name"),t+=assert("undefined"!=typeof s[0].country,"typeof deserialized[0].country != 'undefined'"),t+=assert(s[0].country.name===e.name,"deserialized[0].country.name === country.name"),t?console.log(t+" tests failed."):console.log("No tests failed.")},testReviversAndTransients:function(){var e={_c:{uid:1,type:"Country"},name:"Colombia"},r=function(e,r,n){this._c=circular.register("Person"),this.name=e,this.age=r,this.country=n};circular.registerClass("Person",r,{reviver:function(e,r){r.push(e)},transients:{age:!0}});var n=[new r("Jhon",400,e),new r("Sarah",300,e)];e.leader=n[0];var s=circular.serialize(n),t=new Array,a=(circular.parse(s,t),0);a+=assert(2===t.length,"personList.length === 2"),a+=assert("undefined"!=typeof t[0].country,"typeof personList[0].country != 'undefined'"),a?console.log(a+" tests failed."):console.log("No tests failed.")}};circularTests.runTests(),module.exports=circularTests;


},{"./circular":1}]},{},[2]);
